<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2017-9-16:  9h: 6m
**
*/
function
__patsfun_21__closurerize($env0)
{
  return array(function($cenv, $arg0) { return __patsfun_21($cenv[1], $arg0); }, $env0);
}


function
luckNumberHtml($arg0)
{
//
  $tmpret0 = NULL;
  $tmp1 = NULL;
  $tmp40 = NULL;
//
  __patsflab_luckNumberHtml:
  $tmp1 = ats2phppre_PHParref_nil();
  ATSLIB_056_prelude__gprint_string__1__1($tmp1, "<!DOCTYPE html>");
  ATSLIB_056_prelude__gprint_newline__3__1($tmp1);
  ATSLIB_056_prelude__gprint_string__1__2($tmp1, "<html>");
  ATSLIB_056_prelude__gprint_newline__3__2($tmp1);
  ATSLIB_056_prelude__gprint_string__1__3($tmp1, "<body>");
  ATSLIB_056_prelude__gprint_newline__3__3($tmp1);
  ATSLIB_056_prelude__gprint_string__1__4($tmp1, "<center>");
  ATSLIB_056_prelude__gprint_newline__3__4($tmp1);
  ATSLIB_056_prelude__gprint_string__1__5($tmp1, "<h1>Your randomly generated lucky number(s):</h1>");
  ATSLIB_056_prelude__gprint_newline__3__5($tmp1);
  ATSLIB_056_prelude__gprint_string__1__6($tmp1, "</center>");
  ATSLIB_056_prelude__gprint_newline__3__6($tmp1);
  ATSLIB_056_prelude__gprint_string__1__7($tmp1, "<hr></hr>");
  ATSLIB_056_prelude__gprint_newline__3__7($tmp1);
  ATSLIB_056_prelude__gprint_string__1__8($tmp1, "<ul>");
  ATSLIB_056_prelude__gprint_newline__3__8($tmp1);
  $tmp40 = ats2phppre_int_foreach_method($arg0);
  $tmp40[0]($tmp40, __patsfun_21__closurerize($tmp1));
  ATSLIB_056_prelude__gprint_string__1__12($tmp1, "</ul>");
  ATSLIB_056_prelude__gprint_newline__3__10($tmp1);
  ATSLIB_056_prelude__gprint_string__1__13($tmp1, "<hr></hr>");
  ATSLIB_056_prelude__gprint_newline__3__11($tmp1);
  ATSLIB_056_prelude__gprint_string__1__14($tmp1, "</body>");
  ATSLIB_056_prelude__gprint_newline__3__12($tmp1);
  ATSLIB_056_prelude__gprint_string__1__15($tmp1, "</html>");
  ATSLIB_056_prelude__gprint_newline__3__13($tmp1);
  $tmpret0 = ats2phppre_PHParref_join($tmp1);
  return $tmpret0;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__1($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__1($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__2($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__2($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__3($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__3($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__4($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__4($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__5($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__5($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__6($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__6($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__7($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__7($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__8($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__8($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
myrand_20()
{
//
  $tmpret38 = NULL;
//
  __patsflab_myrand_20:
  $tmpret38 = rand(0, 100);
  return $tmpret38;
} // end-of-function


function
__patsfun_21($env0, $arg0)
{
//
  $tmp48 = NULL;
//
  __patsflab___patsfun_21:
  ATSLIB_056_prelude__gprint_string__1__9($env0, "<li>Lucky number: ");
  $tmp48 = myrand_20();
  ATSLIB_056_prelude__gprint_int__2__1($env0, $tmp48);
  ATSLIB_056_prelude__gprint_string__1__11($env0, "</li>");
  ATSLIB_056_prelude__gprint_newline__3__9($env0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__9($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_int__2__1($env0, $arg0)
{
//
  $tmp4__1 = NULL;
//
  __patsflab_gprint_int:
  $tmp4__1 = ats2phppre_strval($arg0);
  ATSLIB_056_prelude__gprint_string__1__10($env0, $tmp4__1);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__10($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__11($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__9($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__12($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__10($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__13($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__11($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__14($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__12($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__1__15($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__3__13($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
