<?php
/*
**
** The PHP code is generated by atscc2php
** The starting compilation time is: 2017-9-15: 20h:29m
**
*/

function
multable_main()
{
//
  $tmpret50 = NULL;
  $tmp51 = NULL;
//
  __patsflab_multable_main:
  $tmp51 = ats2phppre_PHParref_nil();
  ATSLIB_056_prelude__gprint_string__7__1($tmp51, "<!DOCTYPE html>");
  ATSLIB_056_prelude__gprint_newline__9__1($tmp51);
  _057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__html__0__1($tmp51);
  $tmpret50 = ats2phppre_PHParref_join($tmp51);
  return $tmpret50;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__1($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__1($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__html__0__1($env0)
{
//
//
  __patsflab_html:
  ATSLIB_056_prelude__gprint_string__7__2($env0, "<html>");
  ATSLIB_056_prelude__gprint_newline__9__2($env0);
  _057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__head__1__1($env0);
  _057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__body__2__1($env0);
  ATSLIB_056_prelude__gprint_string__7__23($env0, "</html>");
  ATSLIB_056_prelude__gprint_newline__9__13($env0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__2($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__2($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__head__1__1($env0)
{
//
//
  __patsflab_head:
  ATSLIB_056_prelude__gprint_string__7__3($env0, "<head>");
  ATSLIB_056_prelude__gprint_newline__9__3($env0);
  ATSLIB_056_prelude__gprint_string__7__4($env0, "<meta charset=\"utf-8\">");
  ATSLIB_056_prelude__gprint_newline__9__4($env0);
  ATSLIB_056_prelude__gprint_string__7__5($env0, "</head>");
  ATSLIB_056_prelude__gprint_newline__9__5($env0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__3($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__3($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__4($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__4($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__5($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__5($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__body__2__1($env0)
{
//
//
  __patsflab_body:
  ATSLIB_056_prelude__gprint_string__7__6($env0, "<body>");
  ATSLIB_056_prelude__gprint_newline__9__6($env0);
  ATSLIB_056_prelude__gprint_string__7__7($env0, "<center>\n<h1>Multiplication Table</h1>\n</center>\n");
  ATSLIB_056_prelude__gprint_newline__9__7($env0);
  _057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__multable__5__1($env0);
  ATSLIB_056_prelude__gprint_string__7__22($env0, "</body>");
  ATSLIB_056_prelude__gprint_newline__9__12($env0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__6($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__6($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__7($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__7($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
_057_home_057_hwxi_057_Research_057_ATS_055_Tutoriats_057_BUCS320_057_webpages_057_cs320_055_2017_055_fall_057_src_057_Atscc2php_057_DATS_057_lectures_057_02_057_multable_056_dats__multable__5__1($env0)
{
//
//
  __patsflab_multable:
  ATSLIB_056_prelude__gprint_string__7__8($env0, "<center>");
  ATSLIB_056_prelude__gprint_newline__9__8($env0);
  ATSLIB_056_prelude__gprint_string__7__9($env0, "<table>");
  ATSLIB_056_prelude__gprint_newline__9__9($env0);
  _multable_auxrows_4__4__1($env0, 9);
  ATSLIB_056_prelude__gprint_string__7__20($env0, "</table>");
  ATSLIB_056_prelude__gprint_newline__9__10($env0);
  ATSLIB_056_prelude__gprint_string__7__21($env0, "</center>");
  ATSLIB_056_prelude__gprint_newline__9__11($env0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__8($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__8($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__9($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__9($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
_multable_auxrows_4__4__1($env0, $arg0)
{
//
  $tmp31__1 = NULL;
  $tmp33__1 = NULL;
  $tmp35__1 = NULL;
  $tmp36__1 = NULL;
  $tmp38__1 = NULL;
  $tmp39__1 = NULL;
//
  __patsflab__multable_auxrows_4:
  $tmp31__1 = ats2phppre_gt_int0_int0($arg0, 0);
  if($tmp31__1) {
    $tmp33__1 = ats2phppre_sub_int0_int0($arg0, 1);
    _multable_auxrows_4__4__1($env0, $tmp33__1);
    $tmp36__1 = ats2phppre_mod_int0_int0($arg0, 2);
    $tmp35__1 = ats2phppre_eq_int0_int0($tmp36__1, 0);
    if($tmp35__1) {
      ATSLIB_056_prelude__gprint_string__7__10($env0, "<tr style=\"background:#c0c0c0\">\n");
    } else {
      // ATSINSmove_void;
    } // endif
    $tmp39__1 = ats2phppre_mod_int0_int0($arg0, 2);
    $tmp38__1 = ats2phppre_gt_int0_int0($tmp39__1, 0);
    if($tmp38__1) {
      ATSLIB_056_prelude__gprint_string__7__11($env0, "<tr style=\"background:#ffffff\">\n");
    } else {
      // ATSINSmove_void;
    } // endif
    _multable_auxrow_3__3__1($env0, 1, $arg0);
    ATSLIB_056_prelude__gprint_string__7__19($env0, "</tr>\n");
  } else {
    // ATSINSmove_void;
  } // endif
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__10($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__11($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
_multable_auxrow_3__3__1($env0, $arg0, $arg1)
{
//
  $apy0 = NULL;
  $apy1 = NULL;
  $tmp20__1 = NULL;
  $tmp27__1 = NULL;
  $tmp29__1 = NULL;
//
  __patsflab__multable_auxrow_3:
  $tmp20__1 = ats2phppre_lte_int0_int0($arg0, $arg1);
  if($tmp20__1) {
    ATSLIB_056_prelude__gprint_string__7__12($env0, "<td>");
    ATSLIB_056_prelude__gprint_int__8__1($env0, $arg0);
    ATSLIB_056_prelude__gprint_string__7__14($env0, " x ");
    ATSLIB_056_prelude__gprint_int__8__2($env0, $arg1);
    ATSLIB_056_prelude__gprint_string__7__16($env0, " = ");
    $tmp27__1 = ats2phppre_mul_int0_int0($arg0, $arg1);
    ATSLIB_056_prelude__gprint_int__8__3($env0, $tmp27__1);
    ATSLIB_056_prelude__gprint_string__7__18($env0, "</td>\n");
    $tmp29__1 = ats2phppre_add_int0_int0($arg0, 1);
    // ATStailcalseq_beg
    $apy0 = $tmp29__1;
    $apy1 = $arg1;
    $arg0 = $apy0;
    $arg1 = $apy1;
    goto __patsflab__multable_auxrow_3;
    // ATStailcalseq_end
  } else {
    // ATSINSmove_void;
  } // endif
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__12($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_int__8__1($env0, $arg0)
{
//
  $tmp54__1 = NULL;
//
  __patsflab_gprint_int:
  $tmp54__1 = ats2phppre_strval($arg0);
  ATSLIB_056_prelude__gprint_string__7__13($env0, $tmp54__1);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__13($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__14($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_int__8__2($env0, $arg0)
{
//
  $tmp54__2 = NULL;
//
  __patsflab_gprint_int:
  $tmp54__2 = ats2phppre_strval($arg0);
  ATSLIB_056_prelude__gprint_string__7__15($env0, $tmp54__2);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__15($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__16($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_int__8__3($env0, $arg0)
{
//
  $tmp54__3 = NULL;
//
  __patsflab_gprint_int:
  $tmp54__3 = ats2phppre_strval($arg0);
  ATSLIB_056_prelude__gprint_string__7__17($env0, $tmp54__3);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__17($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__18($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__19($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__20($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__10($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__21($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__11($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__22($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__12($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_string__7__23($env0, $arg0)
{
//
//
  __patsflab_gprint_string:
  ats2phppre_PHParref_extend($env0, $arg0);
  return/*_void*/;
} // end-of-function


function
ATSLIB_056_prelude__gprint_newline__9__13($env0)
{
//
//
  __patsflab_gprint_newline:
  ats2phppre_PHParref_extend($env0, "\n");
  return/*_void*/;
} // end-of-function

/* ****** ****** */

/* end-of-compilation-unit */
?>
